import os
import uuid

from flask import Flask, render_template, request, send_from_directory
from werkzeug.utils import secure_filename


app = Flask(__name__)

UPLOAD_FOLDER = "uploads"

ALLOWED_EXTENSIONS = {
    ".jpg",
    ".jpeg",
    ".png"
}

MAX_UPLOAD_MB = 10

os.makedirs(UPLOAD_FOLDER, exist_ok=True)

app.config["UPLOAD_FOLDER"] = UPLOAD_FOLDER
app.config["MAX_UPLOAD_MB"] = MAX_UPLOAD_MB
app.config["MAX_CONTENT_LENGTH"] = (
    MAX_UPLOAD_MB * 1024 * 1024
)


def allowed_file(filename):

    extension = os.path.splitext(
        filename
    )[1].lower()

    return extension in ALLOWED_EXTENSIONS


@app.route("/", methods=["GET", "POST"])
def home():

    context = {
        "final_result": None,
        "final_score": None,

        "casia_result": None,
        "casia_score": None,

        "cifake_result": None,
        "cifake_score": None,

        "image_file": None,
        "result_comment": None,
    }

    if request.method == "POST":

        file = request.files.get("image")

        if file is None or file.filename == "":
            return render_template(
                "index.html",
                error="Please select an image."
            )

        if not allowed_file(file.filename):
            return render_template(
                "index.html",
                error="Unsupported file type. Please upload a JPG or PNG image."
            )

        filename = (
            f"{uuid.uuid4().hex[:8]}_"
            f"{secure_filename(file.filename)}"
        )

        image_path = os.path.join(
            app.config["UPLOAD_FOLDER"],
            filename
        )

        file.save(image_path)

        context["image_file"] = filename

        try:

            # Load and run CASIA only when needed
            from casia_predict import predict_casia

            casia_result, casia_score = predict_casia(
                image_path
            )

            context["casia_result"] = casia_result
            context["casia_score"] = casia_score

            # If CASIA detects tampering, we already have
            # the final result. No need to run CIFAKE.
            if casia_result == "TAMPERED":

                context["final_result"] = "TAMPERED"
                context["final_score"] = casia_score

                context["result_comment"] = (
                    "This image shows patterns that "
                    "may indicate image tampering "
                    "according to the ELA-based detector."
                )

            else:

                # Load CIFAKE only if CASIA did not detect tampering
                from cifake_predict import predict_cifake

                cifake_result, cifake_score = predict_cifake(
                    image_path
                )

                context["cifake_result"] = cifake_result
                context["cifake_score"] = cifake_score

                if cifake_result == "AI-GENERATED":

                    context["final_result"] = "AI-GENERATED"
                    context["final_score"] = cifake_score

                    context["result_comment"] = (
                        "This image shows patterns that "
                        "are commonly associated with "
                        "AI-generated or synthetic images."
                    )

                else:

                    context["final_result"] = "REAL"
                    context["final_score"] = cifake_score

                    context["result_comment"] = (
                        "The image was not flagged as "
                        "tampered or AI-generated by "
                        "the models."
                    )

        except Exception as e:

            return render_template(
                "index.html",
                error=f"Error while analyzing image: {e}"
            )

    return render_template(
        "index.html",
        **context
    )


@app.route("/uploads/<filename>")
def uploaded_file(filename):

    return send_from_directory(
        app.config["UPLOAD_FOLDER"],
        filename
    )


if __name__ == "__main__":

    app.run(debug=True)